/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Charger001: THREE.Mesh
    Connector001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    Plane002_3: THREE.Mesh
    Plane002_4: THREE.Mesh
    Plane002_5: THREE.Mesh
    Plane002_6: THREE.Mesh
    Ring: THREE.Mesh
  }
  materials: {
    ['Black.002']: THREE.MeshStandardMaterial
    ['Details.002']: THREE.MeshStandardMaterial
    ['Red.002']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['Silver.002']: THREE.MeshStandardMaterial
    ['Dark Green.003']: THREE.MeshStandardMaterial
    ['Grey.002']: THREE.MeshStandardMaterial
    ['Charger Front.002']: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
  }
}

export function EVChargerModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/EVCharger.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} scale={4} position={[0,-1, 0]}>
      <mesh geometry={nodes.Charger001.geometry} material={materials['Black.002']} position={[0.66, 0.87, 0.17]} rotation={[0, 0, -Math.PI / 2]} scale={[0.5, 2, 0.5]} />
      <mesh geometry={nodes.Connector001.geometry} material={materials['Black.002']} position={[1, -0.62, 0.21]} />
      <group position={[0.35, 0.6, 0.21]} rotation={[0, 0, -Math.PI / 2]} scale={[0.15, 1, 0.1]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Details.002']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Red.002']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Glass.002']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Silver.002']} />
        <mesh geometry={nodes.Plane002_4.geometry} material={materials['Dark Green.003']} />
        <mesh geometry={nodes.Plane002_5.geometry} material={materials['Grey.002']} />
        <mesh geometry={nodes.Plane002_6.geometry} material={materials['Charger Front.002']} />
      </group>
      <mesh geometry={nodes.Ring.geometry} material={materials.Grey} position={[0, 0, 0.2]} scale={[1, 0.7, 1]} />
    </group>
  )
}

useGLTF.preload('/models/EVCharger.glb')
