/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lift_Body: THREE.Mesh
    Ceiling: THREE.Mesh
    Lift_Door: THREE.Mesh
    Handle: THREE.Mesh
    Inner_Ceiling: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube009_3: THREE.Mesh
    Cube009_4: THREE.Mesh
    Cube009_5: THREE.Mesh
    Cube009_6: THREE.Mesh
    Cube009_7: THREE.Mesh
    Cube009_8: THREE.Mesh
    Cube009_9: THREE.Mesh
    Cube009_10: THREE.Mesh
    Cube009_11: THREE.Mesh
    Cube009_12: THREE.Mesh
    Cube009_13: THREE.Mesh
    Cube009_14: THREE.Mesh
    Cube009_15: THREE.Mesh
    Cube009_16: THREE.Mesh
    Cube009_17: THREE.Mesh
    Cube010: THREE.Mesh
    Cube010_1: THREE.Mesh
    Cube010_2: THREE.Mesh
    Cube010_3: THREE.Mesh
    Cube010_4: THREE.Mesh
    Cube010_5: THREE.Mesh
    Cube010_6: THREE.Mesh
    Cube010_7: THREE.Mesh
    Cube010_8: THREE.Mesh
    Cube010_9: THREE.Mesh
    Cube010_10: THREE.Mesh
    Cube010_11: THREE.Mesh
    Cube010_12: THREE.Mesh
    Cube010_13: THREE.Mesh
    Cube010_14: THREE.Mesh
    Cube010_15: THREE.Mesh
    Cube010_16: THREE.Mesh
    Cube010_17: THREE.Mesh
    Panel001: THREE.Mesh
    Panel002: THREE.Mesh
    TV001: THREE.Mesh
    TV002: THREE.Mesh
    Cube026: THREE.Mesh
    Cube026_1: THREE.Mesh
    Cube026_2: THREE.Mesh
    Cube026_3: THREE.Mesh
    Cube026_4: THREE.Mesh
    Cube026_5: THREE.Mesh
    Cube026_6: THREE.Mesh
    Cube026_7: THREE.Mesh
    Cube026_8: THREE.Mesh
    Cube026_9: THREE.Mesh
    Cube026_10: THREE.Mesh
    Cube026_11: THREE.Mesh
    Cube026_12: THREE.Mesh
    Cube026_13: THREE.Mesh
    Cube026_14: THREE.Mesh
    Cube026_15: THREE.Mesh
    Cube026_16: THREE.Mesh
    Cube026_17: THREE.Mesh
    Cube026_18: THREE.Mesh
    Cube026_19: THREE.Mesh
    Cube026_20: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    ['Light Metal']: THREE.MeshStandardMaterial
    Silver: THREE.MeshStandardMaterial
    Alarm: THREE.MeshStandardMaterial
    Close: THREE.MeshStandardMaterial
    Open: THREE.MeshStandardMaterial
    ['1']: THREE.MeshStandardMaterial
    ['1M']: THREE.MeshStandardMaterial
    ['2']: THREE.MeshStandardMaterial
    ['3']: THREE.MeshStandardMaterial
    ['4']: THREE.MeshStandardMaterial
    ['5']: THREE.MeshStandardMaterial
    ['6']: THREE.MeshStandardMaterial
    ['7']: THREE.MeshStandardMaterial
    ['8']: THREE.MeshStandardMaterial
    ['9']: THREE.MeshStandardMaterial
    ['10']: THREE.MeshStandardMaterial
    ['11']: THREE.MeshStandardMaterial
    ['12']: THREE.MeshStandardMaterial
    ['13']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function SchindlerLiftModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/SchindlerLift.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, -4, 0]} scale={1.1}>
      <mesh geometry={nodes.Lift_Body.geometry} material={materials.Metal} position={[0.07, 0, 0.09]} scale={[3.22, 0.17, 2.5]} />
      <mesh geometry={nodes.Ceiling.geometry} material={materials.Metal} position={[0.07, 8.57, 0.09]} scale={[3.22, 0.15, 2.5]} />
      <mesh geometry={nodes.Lift_Door.geometry} material={materials['Light Metal']} position={[-3.15, 0, -2.01]} scale={[0.11, 3.65, 2.12]} />
      <mesh geometry={nodes.Handle.geometry} material={materials.Silver} position={[0.14, 3.6, -1.84]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 2.5, 1]} />
      <mesh geometry={nodes.Inner_Ceiling.geometry} material={materials.Metal} position={[0.11, 8.1, 0.08]} scale={[2.65, 0.13, 2]} />
      <group position={[-2.8, 3.78, 2.03]} scale={[0.01, 0.05, 0.05]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Alarm} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Close} />
        <mesh geometry={nodes.Cube009_3.geometry} material={materials.Open} />
        <mesh geometry={nodes.Cube009_4.geometry} material={materials['1']} />
        <mesh geometry={nodes.Cube009_5.geometry} material={materials['1M']} />
        <mesh geometry={nodes.Cube009_6.geometry} material={materials['2']} />
        <mesh geometry={nodes.Cube009_7.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cube009_8.geometry} material={materials['4']} />
        <mesh geometry={nodes.Cube009_9.geometry} material={materials['5']} />
        <mesh geometry={nodes.Cube009_10.geometry} material={materials['6']} />
        <mesh geometry={nodes.Cube009_11.geometry} material={materials['7']} />
        <mesh geometry={nodes.Cube009_12.geometry} material={materials['8']} />
        <mesh geometry={nodes.Cube009_13.geometry} material={materials['9']} />
        <mesh geometry={nodes.Cube009_14.geometry} material={materials['10']} />
        <mesh geometry={nodes.Cube009_15.geometry} material={materials['11']} />
        <mesh geometry={nodes.Cube009_16.geometry} material={materials['12']} />
        <mesh geometry={nodes.Cube009_17.geometry} material={materials['13']} />
      </group>
      <group position={[-2.8, 3.78, -1.56]} scale={[0.01, 0.05, 0.05]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Alarm} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Close} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.Open} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials['1']} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials['1M']} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials['2']} />
        <mesh geometry={nodes.Cube010_7.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cube010_8.geometry} material={materials['4']} />
        <mesh geometry={nodes.Cube010_9.geometry} material={materials['5']} />
        <mesh geometry={nodes.Cube010_10.geometry} material={materials['6']} />
        <mesh geometry={nodes.Cube010_11.geometry} material={materials['7']} />
        <mesh geometry={nodes.Cube010_12.geometry} material={materials['8']} />
        <mesh geometry={nodes.Cube010_13.geometry} material={materials['9']} />
        <mesh geometry={nodes.Cube010_14.geometry} material={materials['10']} />
        <mesh geometry={nodes.Cube010_15.geometry} material={materials['11']} />
        <mesh geometry={nodes.Cube010_16.geometry} material={materials['12']} />
        <mesh geometry={nodes.Cube010_17.geometry} material={materials['13']} />
      </group>
      <mesh geometry={nodes.Panel001.geometry} material={materials.Black} position={[-2.8, 5.1, 1.89]} scale={[0.01, 0.1, 0.15]} />
      <mesh geometry={nodes.Panel002.geometry} material={materials.Black} position={[-2.8, 5.1, -1.72]} scale={[0.01, 0.1, 0.15]} />
      <mesh geometry={nodes.TV001.geometry} material={materials.Black} position={[-2.8, 6.03, 1.89]} scale={[0.01, 0.35, 0.25]} />
      <mesh geometry={nodes.TV002.geometry} material={materials.Black} position={[-2.8, 6.03, -1.71]} scale={[0.01, 0.35, 0.25]} />
      <group position={[0, 4, 0]} scale={[0.01, 0.35, 0.25]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Light Metal']} />
        <mesh geometry={nodes.Cube026_3.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Cube026_4.geometry} material={materials.Alarm} />
        <mesh geometry={nodes.Cube026_5.geometry} material={materials.Close} />
        <mesh geometry={nodes.Cube026_6.geometry} material={materials.Open} />
        <mesh geometry={nodes.Cube026_7.geometry} material={materials['1']} />
        <mesh geometry={nodes.Cube026_8.geometry} material={materials['1M']} />
        <mesh geometry={nodes.Cube026_9.geometry} material={materials['2']} />
        <mesh geometry={nodes.Cube026_10.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cube026_11.geometry} material={materials['4']} />
        <mesh geometry={nodes.Cube026_12.geometry} material={materials['5']} />
        <mesh geometry={nodes.Cube026_13.geometry} material={materials['6']} />
        <mesh geometry={nodes.Cube026_14.geometry} material={materials['7']} />
        <mesh geometry={nodes.Cube026_15.geometry} material={materials['8']} />
        <mesh geometry={nodes.Cube026_16.geometry} material={materials['9']} />
        <mesh geometry={nodes.Cube026_17.geometry} material={materials['10']} />
        <mesh geometry={nodes.Cube026_18.geometry} material={materials['11']} />
        <mesh geometry={nodes.Cube026_19.geometry} material={materials['12']} />
        <mesh geometry={nodes.Cube026_20.geometry} material={materials['13']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SchindlerLift.glb')
