/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube017_1: THREE.Mesh
    Cube017_2: THREE.Mesh
    Cube018: THREE.Mesh
    Cube018_1: THREE.Mesh
    Cube031: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube144: THREE.Mesh
    Cube144_1: THREE.Mesh
    Cube144_2: THREE.Mesh
    Floor001: THREE.Mesh
    Digital_Hub_Logo: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube007_3: THREE.Mesh
    Building_A_Logo: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube006_3: THREE.Mesh
    Cube006_4: THREE.Mesh
    Building_B_Logo: THREE.Mesh
    Building_B001: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Building_C_Logo: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cube005_3: THREE.Mesh
    Building_D_Logo: THREE.Mesh
    Bridge: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cube_4: THREE.Mesh
    Cube_5: THREE.Mesh
    Shelter: THREE.Mesh
    Solar_panels: THREE.Mesh
    Solar_panel_stand: THREE.Mesh
    Cube026: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Satellite: THREE.Mesh
    Satellite001: THREE.Mesh
    Satellite002: THREE.Mesh
    Satellite003: THREE.Mesh
    Cube025: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Shelter_Connection: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
    Cube023_3: THREE.Mesh
    Stairs: THREE.Mesh
    Carpark_Shelter002: THREE.Mesh
    Carpark_Shelter003: THREE.Mesh
    Carpark_Shelter004: THREE.Mesh
    Carpark_Shelter005: THREE.Mesh
    Carpark_Shelter006: THREE.Mesh
    Carpark_Shelter007: THREE.Mesh
    Carpark_Shelter008: THREE.Mesh
    Carpark_Shelter009: THREE.Mesh
    Carpark_Shelter010: THREE.Mesh
    Perimeter011: THREE.Mesh
    Perimeter012: THREE.Mesh
    Perimeter013: THREE.Mesh
    Perimeter014: THREE.Mesh
    Perimeter015: THREE.Mesh
    Perimeter016: THREE.Mesh
    Perimeter017: THREE.Mesh
    Perimeter018: THREE.Mesh
    Floor: THREE.Mesh
    Cube105: THREE.Mesh
    Cube105_1: THREE.Mesh
    Cube105_2: THREE.Mesh
    Cube105_3: THREE.Mesh
    Cube105_4: THREE.Mesh
    Cube105_5: THREE.Mesh
    Cube105_6: THREE.Mesh
    Carpark_Shelter014: THREE.Mesh
    Carpark_Shelter017: THREE.Mesh
    Carpark_Shelter018: THREE.Mesh
    Road_Shelter001: THREE.Mesh
    Road_Shelter003: THREE.Mesh
    Carpark_Shelter019: THREE.Mesh
    Carpark_Shelter020: THREE.Mesh
    Cube156: THREE.Mesh
    Cube156_1: THREE.Mesh
    Cube156_2: THREE.Mesh
    Carpark_Shelter021: THREE.Mesh
    Carpark_Shelter022: THREE.Mesh
    Carpark_Shelter023: THREE.Mesh
    Carpark_Shelter024: THREE.Mesh
    Carpark_Shelter025: THREE.Mesh
    Carpark_Shelter028: THREE.Mesh
    Building_A_Logo001: THREE.Mesh
    Road_Shelter002: THREE.Mesh
    Cube162: THREE.Mesh
    Cube162_1: THREE.Mesh
    Road_Shelter: THREE.Mesh
    Cube016_1: THREE.Mesh
    Cube016_2: THREE.Mesh
    Cube016_3: THREE.Mesh
    Cube016_4: THREE.Mesh
    Cube016_5: THREE.Mesh
    Cube051: THREE.Mesh
    Cube051_1: THREE.Mesh
    Cube053: THREE.Mesh
    Cube053_1: THREE.Mesh
    Shelter001: THREE.Mesh
    Shelter002: THREE.Mesh
    Cylinder002: THREE.Mesh
    Satellite004: THREE.Mesh
    Satellite005: THREE.Mesh
    Satellite006: THREE.Mesh
    Satellite007: THREE.Mesh
    Cube161: THREE.Mesh
    Cube161_1: THREE.Mesh
    Perimeter020: THREE.Mesh
  }
  materials: {
    ['Off-white']: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Fence: THREE.MeshStandardMaterial
    ['TNS side fence']: THREE.MeshStandardMaterial
    ['Dark grey']: THREE.MeshStandardMaterial
    ['Digital Hub Text']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Building A Logo']: THREE.MeshStandardMaterial
    ['STEng logo']: THREE.MeshStandardMaterial
    ['Building B Logo']: THREE.MeshStandardMaterial
    ['Building C Logo']: THREE.MeshStandardMaterial
    ['Building D Logo']: THREE.MeshStandardMaterial
    ['Solar panel']: THREE.MeshStandardMaterial
    ['Light beige']: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    ['Light Grey']: THREE.MeshStandardMaterial
    ['Grey beige']: THREE.MeshStandardMaterial
  }
}

export function STEngAMKModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/STEngAMK.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} position={[10, 0, -10]} scale={0.1}>
      <group position={[-8.36, 0, 25.18]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Grey} />
      </group>
      <group position={[-4.06, 0, 32.18]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials.Grey} />
      </group>
      <group position={[-13.57, 0, 64.71]} rotation={[0, Math.PI / 2, 0]} scale={[-7.5, -1.3, -5]}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.Grey} />
      </group>
      <group position={[-10.13, 2.8, 141.19]} scale={[2, 0.1, 1.5]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials.Orange} />
      </group>
      <group position={[-14.96, 0, 146.61]}>
        <mesh geometry={nodes.Cube144.geometry} material={materials.Fence} />
        <mesh geometry={nodes.Cube144_1.geometry} material={materials['TNS side fence']} />
        <mesh geometry={nodes.Cube144_2.geometry} material={materials.Orange} />
      </group>
      <mesh geometry={nodes.Floor001.geometry} material={materials['Dark grey']} position={[-14.96, 0, 146.61]} />
      <mesh geometry={nodes.Digital_Hub_Logo.geometry} material={materials['Digital Hub Text']} position={[-13.44, 7.46, 28.79]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59} />
      <group position={[5.84, 0, 1.63]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.Orange} />
      </group>
      <mesh geometry={nodes.Building_A_Logo.geometry} material={materials['Building A Logo']} position={[5.8, 7.46, 11.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59} />
      <group position={[0.97, 0, 24.95]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['STEng logo']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials.Grey} />
      </group>
      <mesh geometry={nodes.Building_B_Logo.geometry} material={materials['Building B Logo']} position={[0.92, 7.46, 27.76]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59} />
      <mesh geometry={nodes.Building_B001.geometry} material={materials.Grey} position={[0.93, 0, 44.06]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Grey} position={[0.97, 0, 48.05]} scale={[1, 0.71, 1]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.Grey} position={[1.77, 0, 48.05]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.71, 1]} />
      <group position={[0.97, 0, 48.05]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Cube047.geometry} material={materials.Grey} position={[0.97, 0, 71.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.71, 1]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials.Orange} position={[2.39, 0, 71.5]} scale={[1, 1, 2.5]} />
      <mesh geometry={nodes.Building_C_Logo.geometry} material={materials['Building C Logo']} position={[0.96, 5.11, 52.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59} />
      <group position={[0, 0, 86.13]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.Orange} />
      </group>
      <mesh geometry={nodes.Building_D_Logo.geometry} material={materials['Building D Logo']} position={[-0.02, 7.45, 89.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.59} />
      <mesh geometry={nodes.Bridge.geometry} material={materials['Off-white']} position={[44.36, 4.5, 15.39]} rotation={[0, Math.PI / 2, 0]} scale={[-4.15, -0.5, -1.75]} />
      <group position={[15.78, 17, 23.37]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Cube023.geometry} material={materials.Grey} position={[-74.54, 35, 214.64]} rotation={[-Math.PI, 1.36, -Math.PI]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.Grey} position={[-176.7, 35, 200.46]} rotation={[0, 0.22, 0]} />
      <group position={[-138.58, 15.28, 183.28]} rotation={[0, 0.22, 0]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Dark grey']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials['STEng logo']} />
      </group>
      <mesh geometry={nodes.Shelter.geometry} material={materials.Orange} position={[-79.59, 4.5, 190.8]} rotation={[0, 0.24, 0]} />
      <mesh geometry={nodes.Solar_panels.geometry} material={materials['Solar panel']} position={[-168.23, 35.58, 215.69]} rotation={[0.53, 0.19, -0.11]} scale={[17.5, 0.05, 1]} />
      <mesh geometry={nodes.Solar_panel_stand.geometry} material={materials['Solar panel']} position={[-168.6, 35.1, 214.01]} rotation={[0, 0.22, 0]} scale={[0.09, 0.75, 0.05]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.Grey} position={[-207.08, 0, 268.32]} rotation={[0, 1.56, 0]} scale={[4, 7.5, 4]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Grey} position={[-192.78, 35, 211.12]} rotation={[0, 0.22, 0]} scale={[1, 1.33, 1]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Grey} position={[-109.09, 23.3, 243.17]} rotation={[0, 0.22, 0]} scale={[1, 1.33, 1]} />
      <mesh geometry={nodes.Satellite.geometry} material={nodes.Satellite.material} position={[-200.94, 27.4, 251.59]} rotation={[0, -0.24, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite001.geometry} material={nodes.Satellite001.material} position={[-180.96, 27.4, 248.1]} rotation={[0, -0.24, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite002.geometry} material={nodes.Satellite002.material} position={[-161.2, 27.4, 244.85]} rotation={[0, -0.24, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite003.geometry} material={nodes.Satellite003.material} position={[-136.48, 23.4, 240.24]} rotation={[0, -0.24, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.Grey} position={[-119.22, 23.3, 239.05]} rotation={[0, 0.22, 0]} scale={[3, 1.3, 1]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Grey} position={[-75.49, 23.3, 230.49]} rotation={[0, 0.22, 0]} scale={[3, 1.3, 1]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.Grey} position={[-95.09, 23.3, 223.79]} rotation={[0, 0.22, 0]} scale={[1.5, 1.3, 1]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.Grey} position={[-176.51, 37, 200.14]} rotation={[0, 0.22, 0]} scale={[1.1, 0.15, 1.02]} />
      <mesh geometry={nodes.Shelter_Connection.geometry} material={materials.Orange} position={[-219.26, 5, 241]} rotation={[-Math.PI, 1.35, -Math.PI]} scale={[0.6, 0.15, 1.08]} />
      <group position={[-132.5, 5, 181.29]} rotation={[0, 0.22, 0]} scale={[2.02, 2.33, 0.69]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Off-white']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube023_3.geometry} material={materials.Grey} />
      </group>
      <mesh geometry={nodes.Stairs.geometry} material={nodes.Stairs.material} position={[-143.17, 0, 180.89]} rotation={[Math.PI, 1.35, Math.PI / 2]} scale={[0.1, 0.1, 4]} />
      <mesh geometry={nodes.Carpark_Shelter002.geometry} material={materials.Orange} position={[-236.87, 2.8, 196.73]} rotation={[0, 0.22, 0]} scale={[0.04, 0.4, 2.43]} />
      <mesh geometry={nodes.Carpark_Shelter003.geometry} material={materials['Off-white']} position={[-236.87, 0, 196.73]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter004.geometry} material={materials['Off-white']} position={[-233.94, 0, 196.08]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter005.geometry} material={materials['Off-white']} position={[-232.21, 0, 203.9]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter006.geometry} material={materials['Off-white']} position={[-235.14, 0, 204.53]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter007.geometry} material={materials['Off-white']} position={[-233.46, 0.3, 212.11]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter008.geometry} material={materials['Off-white']} position={[-230.54, 0.3, 211.41]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter009.geometry} material={materials.Orange} position={[-232.24, 4.8, 208.96]} rotation={[0, 0.22, 0]} scale={[0.07, 0.53, 0.57]} />
      <mesh geometry={nodes.Carpark_Shelter010.geometry} material={materials['Off-white']} position={[-231.45, 3.1, 210.41]} rotation={[0, 0.22, 0]} scale={[0.01, 2.27, 0.07]} />
      <mesh geometry={nodes.Perimeter011.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter012.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter013.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter014.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter015.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter016.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Perimeter017.geometry} material={materials.Fence} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} scale={[1, 2, 1]} />
      <mesh geometry={nodes.Perimeter018.geometry} material={materials['Light beige']} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} scale={[1, 5, 1]} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Dark grey']} position={[-216.8, 0, 291.9]} rotation={[0, 0.22, 0]} />
      <group position={[-319.3, 15.9, 267.45]} rotation={[0, 0.22, 0]} scale={[1, 4, 3.5]}>
        <mesh geometry={nodes.Cube105.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube105_1.geometry} material={materials['Light beige']} />
        <mesh geometry={nodes.Cube105_2.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cube105_3.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube105_4.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube105_5.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube105_6.geometry} material={materials['Dark grey']} />
      </group>
      <mesh geometry={nodes.Carpark_Shelter014.geometry} material={materials['Off-white']} position={[-327.54, 0, 315.64]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter017.geometry} material={materials['Off-white']} position={[-329.64, 0, 306.38]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter018.geometry} material={materials.Orange} position={[-240.99, 2.8, 291.54]} rotation={[0, 0.22, 0]} scale={[0.5, 0.4, 0.71]} />
      <mesh geometry={nodes.Road_Shelter001.geometry} material={materials.Orange} position={[-326.94, 5, 316.02]} rotation={[0, 0.22, 0]} scale={[2, 0.38, 0.4]} />
      <mesh geometry={nodes.Road_Shelter003.geometry} material={materials.Orange} position={[-259.92, 5, 296.49]} rotation={[0, 0.22, 0]} scale={[1.2, 0.38, 0.24]} />
      <mesh geometry={nodes.Carpark_Shelter019.geometry} material={materials['Off-white']} position={[-264.91, 0, 301.45]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter020.geometry} material={materials['Off-white']} position={[-240.91, 0, 296.13]} rotation={[0, 0.22, 0]} scale={[0.01, 3.73, 0.07]} />
      <group position={[-340.54, 0, 319.58]} rotation={[0, 0.22, 0]} scale={[1, 2, 0.93]}>
        <mesh geometry={nodes.Cube156.geometry} material={materials.Fence} />
        <mesh geometry={nodes.Cube156_1.geometry} material={materials['Light beige']} />
        <mesh geometry={nodes.Cube156_2.geometry} material={materials['Dark grey']} />
      </group>
      <mesh geometry={nodes.Carpark_Shelter021.geometry} material={materials['Off-white']} position={[-232.8, 0, 221.73]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter022.geometry} material={materials['Off-white']} position={[-246.96, 0, 224.86]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter023.geometry} material={materials['Off-white']} position={[-244.68, 0, 235.12]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter024.geometry} material={materials['Off-white']} position={[-230.53, 0, 231.98]} rotation={[0, 0.22, 0]} scale={[0.01, 6.67, 0.07]} />
      <mesh geometry={nodes.Carpark_Shelter025.geometry} material={materials['Off-white']} position={[-340.49, 0, 317.44]} rotation={[0, 0.22, 0]} scale={[0, 3.07, 0.03]} />
      <mesh geometry={nodes.Carpark_Shelter028.geometry} material={materials['Off-white']} position={[-265.78, 3.06, 297.19]} rotation={[0, 0.22, 0]} scale={[0.01, 2.67, 0.07]} />
      <mesh geometry={nodes.Building_A_Logo001.geometry} material={materials['Digital Hub Text']} position={[-338.14, 9.81, 311.27]} rotation={[Math.PI / 2, 0, -1.79]} scale={0.59} />
      <mesh geometry={nodes.Road_Shelter002.geometry} material={materials.Orange} position={[-336.7, 2.3, 318.18]} rotation={[0, 0.22, 0]} scale={[0.72, 0.2, 0.06]} />
      <group position={[-338.41, 0, 301.36]} rotation={[-Math.PI, 1.35, -Math.PI]} scale={[1, 1, 0.76]}>
        <mesh geometry={nodes.Cube162.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube162_1.geometry} material={materials.Orange} />
      </group>
      <mesh geometry={nodes.Road_Shelter.geometry} material={materials.Orange} position={[-229.93, 5, 232.36]} rotation={[0, 0.22, 0]} scale={[3, 0.38, 0.44]} />
      <group position={[-141.8, 0, 47.77]} rotation={[0, 0.22, 0]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['Light beige']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cube016_3.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube016_4.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube016_5.geometry} material={materials['STEng logo']} />
      </group>
      <group position={[-141.8, 0, 47.78]} rotation={[0, 0.22, 0]}>
        <mesh geometry={nodes.Cube051.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube051_1.geometry} material={materials['STEng logo']} />
      </group>
      <group position={[-145.73, 30, 95.81]} rotation={[0, 0.22, 0]} scale={[1.2, 1, 1]}>
        <mesh geometry={nodes.Cube053.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube053_1.geometry} material={materials['Light beige']} />
      </group>
      <mesh geometry={nodes.Shelter001.geometry} material={materials.Grey} position={[-175.97, 9.52, 55.35]} rotation={[0, 0.22, 0]} scale={[10, 0.25, 2]} />
      <mesh geometry={nodes.Shelter002.geometry} material={materials['Grey beige']} position={[-148.25, 3, 46.14]} rotation={[0, 0.22, 0]} scale={[7.5, 0.2, 2]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Grey} position={[-163.17, 30.5, 96.31]} rotation={[0, 0.22, 0]} />
      <mesh geometry={nodes.Satellite004.geometry} material={nodes.Satellite004.material} position={[-144.71, 30, 137.5]} rotation={[0, -0.02, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite005.geometry} material={nodes.Satellite005.material} position={[-134.2, 30, 117.64]} rotation={[0, -0.02, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite006.geometry} material={nodes.Satellite006.material} position={[-132.23, 30, 127.38]} rotation={[0, -0.02, 0]} scale={[2, 0.1, 2]} />
      <mesh geometry={nodes.Satellite007.geometry} material={nodes.Satellite007.material} position={[-130.52, 30, 135.66]} rotation={[0, -0.02, 0]} scale={[2, 0.1, 2]} />
      <group position={[-183.84, 0, 45.58]} rotation={[0, 0.22, 0]}>
        <mesh geometry={nodes.Cube161.geometry} material={materials.Fence} />
        <mesh geometry={nodes.Cube161_1.geometry} material={materials.Orange} />
      </group>
      <mesh geometry={nodes.Perimeter020.geometry} material={materials['Dark grey']} position={[-183.84, 0, 45.58]} rotation={[0, 0.22, 0]} scale={[9.18, 0.5, 26.32]} />
    </group>
  )
}

useGLTF.preload('/models/STEngAMK.glb')
