/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Upper_Floor_With_Balcony_(Reference)']: THREE.Mesh
    Lift_1: THREE.Mesh
    Lift_2: THREE.Mesh
    Cargo_Lift: THREE.Mesh
    Lift_3: THREE.Mesh
    Lift_4: THREE.Mesh
    Back_Lift: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube563: THREE.Mesh
    Cube563_1: THREE.Mesh
    Cube563_2: THREE.Mesh
    Lift_Lobby_Stairs_1: THREE.Mesh
    Lift_Lobby_Stairs_to_Outside: THREE.Mesh
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane004_3: THREE.Mesh
    Old_Building_Back_Stairs_1: THREE.Mesh
    Cube011: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    Cube011_3: THREE.Mesh
    Cube011_4: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube012_2: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Back_Stairs_1: THREE.Mesh
    Cafe_Bench: THREE.Mesh
    Seats001: THREE.Mesh
    Reception_Desk: THREE.Mesh
    Pillars_1: THREE.Mesh
    Room_at_back: THREE.Mesh
    Back_Stairs_To_Outside: THREE.Mesh
    Old_Building_Back_Outside_Steps: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_1002: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_1: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_1001: THREE.Mesh
    Poles: THREE.Mesh
    Fan_boxes: THREE.Mesh
    Parking_Lot_Back_Wheel_Stops: THREE.Mesh
    Cube612: THREE.Mesh
    Cube612_1: THREE.Mesh
    Cube612_2: THREE.Mesh
    Cube612_3: THREE.Mesh
    Lift_Lobby_Stairs_1M: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_1M: THREE.Mesh
    Pillars_1M: THREE.Mesh
    EV_charger: THREE.Mesh
    EV_charger001: THREE.Mesh
    EV_charger002: THREE.Mesh
    Fan_boxes002: THREE.Mesh
    Poles003: THREE.Mesh
    Parking_Lot_Back_Wheel_Stops008: THREE.Mesh
    Cube611: THREE.Mesh
    Cube611_1: THREE.Mesh
    Cube611_2: THREE.Mesh
    Cube611_3: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Lift_Lobby_Stairs_2: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_2: THREE.Mesh
    Back_Stairs_2: THREE.Mesh
    Old_Building_Back_Stairs_2: THREE.Mesh
    Pillars_2: THREE.Mesh
    Parking_Lot_Back_Wheel_Stops018: THREE.Mesh
    Cube552: THREE.Mesh
    Cube552_1: THREE.Mesh
    Cube552_2: THREE.Mesh
    Cube552_3: THREE.Mesh
    Poles001: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Lift_Lobby_Stairs_3: THREE.Mesh
    Back_Stairs_3: THREE.Mesh
    Old_Building_Back_Stairs_3: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_3: THREE.Mesh
    Pillars_3: THREE.Mesh
    Parking_Lot_Back_Wheel_Stops037: THREE.Mesh
    Cube545: THREE.Mesh
    Cube545_1: THREE.Mesh
    Cube545_2: THREE.Mesh
    Cube545_3: THREE.Mesh
    Poles002: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Back_Stairs_4: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_4: THREE.Mesh
    Lift_Lobby_Stairs_4: THREE.Mesh
    Pillars_4: THREE.Mesh
    Cube425: THREE.Mesh
    Cube425_1: THREE.Mesh
    Cube425_2: THREE.Mesh
    Cube425_3: THREE.Mesh
    Lift_Lobby_Stairs_5: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_5: THREE.Mesh
    Back_Stairs_5: THREE.Mesh
    Pillars_5: THREE.Mesh
    Circle_Things_for_Trees: THREE.Mesh
    Grass_Patches: THREE.Mesh
    Cube541: THREE.Mesh
    Cube541_1: THREE.Mesh
    Cube541_2: THREE.Mesh
    Cube541_3: THREE.Mesh
    Old_Building_Roof: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_6: THREE.Mesh
    Lift_Lobby_Stairs_6: THREE.Mesh
    Pillars_6: THREE.Mesh
    Cube640: THREE.Mesh
    Cube640_1: THREE.Mesh
    Cube640_2: THREE.Mesh
    Cube640_3: THREE.Mesh
    Cube640_4: THREE.Mesh
    Lift_Lobby_Stairs_7: THREE.Mesh
    Lift_Lobby_Stairs_7001: THREE.Mesh
    Pillars_7: THREE.Mesh
    Cube1067: THREE.Mesh
    Cube1067_1: THREE.Mesh
    Cube1067_2: THREE.Mesh
    Cube1067_3: THREE.Mesh
    Cube1067_4: THREE.Mesh
    Lift_Lobby_Stairs_8: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_8: THREE.Mesh
    Pillars_8: THREE.Mesh
    Cube1068: THREE.Mesh
    Cube1068_1: THREE.Mesh
    Cube1068_2: THREE.Mesh
    Cube1068_3: THREE.Mesh
    Cube1068_4: THREE.Mesh
    Lift_Lobby_Stairs_9: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_9: THREE.Mesh
    Seats: THREE.Mesh
    Pillars_9: THREE.Mesh
    Table006: THREE.Mesh
    Table007: THREE.Mesh
    Cube1069: THREE.Mesh
    Cube1069_1: THREE.Mesh
    Cube1069_2: THREE.Mesh
    Cube1069_3: THREE.Mesh
    Cube1069_4: THREE.Mesh
    Lift_Lobby_Stairs_10: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_10: THREE.Mesh
    Pillars_10: THREE.Mesh
    Cube1070: THREE.Mesh
    Cube1070_1: THREE.Mesh
    Cube1070_2: THREE.Mesh
    Cube1070_3: THREE.Mesh
    Cube1070_4: THREE.Mesh
    Lift_Lobby_Stairs_11: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_11: THREE.Mesh
    Pillars_11: THREE.Mesh
    Cube1071: THREE.Mesh
    Cube1071_1: THREE.Mesh
    Cube1071_2: THREE.Mesh
    Cube1071_3: THREE.Mesh
    Cube1071_4: THREE.Mesh
    Lift_Lobby_Stairs_12: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_12: THREE.Mesh
    Pillars_12: THREE.Mesh
    Cargo_Lift_Lobby_Stairs_13: THREE.Mesh
    Cube252: THREE.Mesh
    Cube252_1: THREE.Mesh
    Cube252_2: THREE.Mesh
    Cube252_3: THREE.Mesh
    Cube252_4: THREE.Mesh
    Cube252_5: THREE.Mesh
    Lift_Lobby_Stairs_13: THREE.Mesh
    Pillars_13: THREE.Mesh
    Cube638: THREE.Mesh
    Cube638_1: THREE.Mesh
    Cube638_2: THREE.Mesh
  }
  materials: {
    ['Dark Grey']: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    ['Light Grey']: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Fence (Sides)']: THREE.MeshStandardMaterial
    ['Wire Fence']: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    ['STEng Logo']: THREE.MeshStandardMaterial
    ['Room Material']: THREE.MeshStandardMaterial
    Greenery: THREE.MeshStandardMaterial
    Toilets: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
  }
}

export function STEngJEModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/STEngJE.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, -3, 0]} scale={0.12}>
      <mesh geometry={nodes['Upper_Floor_With_Balcony_(Reference)'].geometry} material={nodes['Upper_Floor_With_Balcony_(Reference)'].material} position={[-35.47, 38.09, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]} />
      <mesh geometry={nodes.Lift_1.geometry} material={materials['Dark Grey']} position={[-37.09, 1.05, -30.92]} />
      <mesh geometry={nodes.Lift_2.geometry} material={materials['Dark Grey']} position={[-37.12, 1.05, -33.23]} />
      <mesh geometry={nodes.Cargo_Lift.geometry} material={materials['Dark Grey']} position={[-12.27, 1.05, -22.48]} />
      <mesh geometry={nodes.Lift_3.geometry} material={materials['Dark Grey']} position={[-32.95, 1.05, -30.92]} />
      <mesh geometry={nodes.Lift_4.geometry} material={materials['Dark Grey']} position={[-32.98, 1.05, -33.23]} />
      <mesh geometry={nodes.Back_Lift.geometry} material={materials.Blue} position={[-2.69, 1.05, -11.98]} />
      <group position={[-46.06, 0.15, -22.92]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Light Grey']} />
      </group>
      <group position={[-40.94, 5.64, -19.91]}>
        <mesh geometry={nodes.Cube563.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube563_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube563_2.geometry} material={materials['Dark Grey']} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_1.geometry} material={nodes.Lift_Lobby_Stairs_1.material} position={[-37.62, 1.05, -29.58]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Lift_Lobby_Stairs_to_Outside.geometry} material={nodes.Lift_Lobby_Stairs_to_Outside.material} position={[-38.97, 0.15, -34.73]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <group position={[-40.95, 1.05, -27.6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Plane004_3.geometry} material={materials['Light Grey']} />
      </group>
      <mesh geometry={nodes.Old_Building_Back_Stairs_1.geometry} material={nodes.Old_Building_Back_Stairs_1.material} position={[0.27, 1.05, -18.75]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <group position={[-71.55, 0, 29.81]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Dark Grey']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Fence (Sides)']} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['Wire Fence']} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials.Road} />
      </group>
      <group position={[-61.55, 0, 7.54]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Dark Grey']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['STEng Logo']} />
      </group>
      <group position={[-49.89, 0, -69.03]} rotation={[0, -0.75, 0]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Dark Grey']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Back_Stairs_1.geometry} material={nodes.Back_Stairs_1.material} position={[3.44, 0, 21.25]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cafe_Bench.geometry} material={nodes.Cafe_Bench.material} position={[-34.15, 1.05, -42.29]} rotation={[-Math.PI, 0.74, -Math.PI]} />
      <mesh geometry={nodes.Seats001.geometry} material={nodes.Seats001.material} position={[-35.74, 1.05, -20.97]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Reception_Desk.geometry} material={nodes.Reception_Desk.material} position={[-33.36, 1.05, -24.78]} />
      <mesh geometry={nodes.Pillars_1.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Room_at_back.geometry} material={nodes.Room_at_back.material} position={[17.06, 0, 9.81]} rotation={[0, 0.84, 0]} />
      <mesh geometry={nodes.Back_Stairs_To_Outside.geometry} material={nodes.Back_Stairs_To_Outside.material} position={[5.19, 0, -23.57]} rotation={[Math.PI / 2, 0, -2.39]} />
      <mesh geometry={nodes.Old_Building_Back_Outside_Steps.geometry} material={nodes.Old_Building_Back_Outside_Steps.material} position={[5.56, 0.15, 16.58]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_1002.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_1002.material} position={[-3.71, 3.05, -19.19]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_1.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_1.material} position={[0.45, 1.05, -22.75]} rotation={[Math.PI / 2, 0, -2.37]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_1001.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_1001.material} position={[-0.5, 2.45, -21.74]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Poles.geometry} material={materials['Light Grey']} position={[-53.16, 5.65, -26.89]} />
      <mesh geometry={nodes.Fan_boxes.geometry} material={materials['Dark Grey']} position={[-46.7, 5.65, -21.27]} />
      <mesh geometry={nodes.Parking_Lot_Back_Wheel_Stops.geometry} material={materials['Light Grey']} position={[-46.34, 5.65, -21.96]} />
      <group position={[-33.93, 5.65, -19.83]}>
        <mesh geometry={nodes.Cube612.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube612_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube612_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube612_3.geometry} material={materials['Room Material']} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_1M.geometry} material={nodes.Lift_Lobby_Stairs_1M.material} position={[-37.58, 5.65, -32.35]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_1M.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_1M.material} position={[-3.31, 5.65, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_1M.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.EV_charger.geometry} material={nodes.EV_charger.material} position={[3.13, 6.4, -9.3]} />
      <mesh geometry={nodes.EV_charger001.geometry} material={nodes.EV_charger001.material} position={[9.65, 6.4, -11.78]} rotation={[0, 0.87, 0]} />
      <mesh geometry={nodes.EV_charger002.geometry} material={nodes.EV_charger002.material} position={[12.64, 6.4, -15.23]} rotation={[0, 0.87, 0]} />
      <mesh geometry={nodes.Fan_boxes002.geometry} material={nodes.Fan_boxes002.material} position={[4.87, 5.65, -9.83]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Poles003.geometry} material={materials['Light Grey']} position={[-53.16, 9.25, -26.89]} />
      <mesh geometry={nodes.Parking_Lot_Back_Wheel_Stops008.geometry} material={materials['Light Grey']} position={[-46.34, 9.25, -20.78]} />
      <group position={[-33.93, 9.26, -19.83]}>
        <mesh geometry={nodes.Cube611.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube611_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube611_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube611_3.geometry} material={materials['Room Material']} />
      </group>
      <group position={[-33.93, 6.45, -19.83]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_2.geometry} material={nodes.Lift_Lobby_Stairs_2.material} position={[-37.58, 9.25, -32.37]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_2.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_2.material} position={[-3.31, 9.26, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Back_Stairs_2.geometry} material={nodes.Back_Stairs_2.material} position={[3.21, 9.25, 18.64]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Old_Building_Back_Stairs_2.geometry} material={nodes.Old_Building_Back_Stairs_2.material} position={[-3.06, 6.45, -13.93]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_2.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Parking_Lot_Back_Wheel_Stops018.geometry} material={materials['Light Grey']} position={[-46.34, 12.85, -20.78]} />
      <group position={[-33.93, 12.85, -19.83]}>
        <mesh geometry={nodes.Cube552.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube552_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube552_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube552_3.geometry} material={materials['Room Material']} />
      </group>
      <mesh geometry={nodes.Poles001.geometry} material={materials['Light Grey']} position={[-53.16, 12.85, -26.89]} />
      <group position={[-33.93, 11.85, -19.83]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_3.geometry} material={nodes.Lift_Lobby_Stairs_3.material} position={[-37.58, 12.85, -32.35]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Back_Stairs_3.geometry} material={nodes.Back_Stairs_3.material} position={[3.21, 12.85, 18.64]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Old_Building_Back_Stairs_3.geometry} material={nodes.Old_Building_Back_Stairs_3.material} position={[-3.06, 12.86, -13.93]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_3.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_3.material} position={[-3.31, 12.87, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_3.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Parking_Lot_Back_Wheel_Stops037.geometry} material={materials['Light Grey']} position={[-46.34, 16.45, -20.78]} />
      <group position={[-33.93, 16.45, -19.83]}>
        <mesh geometry={nodes.Cube545.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube545_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube545_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube545_3.geometry} material={materials['Room Material']} />
      </group>
      <mesh geometry={nodes.Poles002.geometry} material={materials['Light Grey']} position={[-53.16, 16.45, -26.89]} />
      <group position={[-33.93, 18.26, -19.83]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Back_Stairs_4.geometry} material={nodes.Back_Stairs_4.material} position={[3.21, 16.45, 18.64]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_4.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_4.material} position={[-3.31, 16.47, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Lift_Lobby_Stairs_4.geometry} material={nodes.Lift_Lobby_Stairs_4.material} position={[-37.58, 16.45, -32.35]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Pillars_4.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-33.93, 20.05, -19.18]}>
        <mesh geometry={nodes.Cube425.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube425_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube425_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube425_3.geometry} material={materials['Room Material']} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_5.geometry} material={nodes.Lift_Lobby_Stairs_5.material} position={[-37.58, 20.05, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_5.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_5.material} position={[-4.36, 20.06, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Back_Stairs_5.geometry} material={nodes.Back_Stairs_5.material} position={[2.17, 20.05, 18.64]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_5.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Circle_Things_for_Trees.geometry} material={materials.Grey} position={[10.53, 25.25, 16.07]} />
      <mesh geometry={nodes.Grass_Patches.geometry} material={materials.Greenery} position={[3.02, 25.25, -16.17]} />
      <group position={[-33.93, 25.25, -19.83]}>
        <mesh geometry={nodes.Cube541.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube541_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube541_2.geometry} material={materials.Greenery} />
        <mesh geometry={nodes.Cube541_3.geometry} material={materials.Toilets} />
      </group>
      <mesh geometry={nodes.Old_Building_Roof.geometry} material={materials.Grey} position={[-33.93, 24.67, -19.83]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_6.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_6.material} position={[-2.79, 25.25, -21.71]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.5, 1, 0.1]} />
      <mesh geometry={nodes.Lift_Lobby_Stairs_6.geometry} material={nodes.Lift_Lobby_Stairs_6.material} position={[-37.58, 25.25, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Pillars_6.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 37.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube640.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube640_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube640_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube640_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube640_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_7.geometry} material={nodes.Lift_Lobby_Stairs_7.material} position={[-4.36, 37.86, -21.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Lift_Lobby_Stairs_7001.geometry} material={nodes.Lift_Lobby_Stairs_7001.material} position={[-37.58, 37.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Pillars_7.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 42.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube1067.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube1067_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube1067_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube1067_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube1067_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_8.geometry} material={nodes.Lift_Lobby_Stairs_8.material} position={[-37.58, 42.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_8.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_8.material} position={[-4.36, 42.86, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_8.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 47.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube1068.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube1068_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube1068_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube1068_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube1068_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_9.geometry} material={nodes.Lift_Lobby_Stairs_9.material} position={[-37.58, 47.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_9.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_9.material} position={[-4.36, 47.86, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Seats.geometry} material={nodes.Seats.material} position={[-25.28, 47.85, -51.76]} rotation={[0, -0.75, 0]} />
      <mesh geometry={nodes.Pillars_9.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Table006.geometry} material={nodes.Table006.material} position={[-24.21, 48.9, -45.54]} rotation={[0, -0.75, 0]} />
      <mesh geometry={nodes.Table007.geometry} material={nodes.Table007.material} position={[-20.83, 48.9, -49.13]} rotation={[0, -0.75, 0]} />
      <group position={[-35.47, 52.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube1069.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube1069_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube1069_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube1069_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube1069_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_10.geometry} material={nodes.Lift_Lobby_Stairs_10.material} position={[-37.58, 52.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_10.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_10.material} position={[-4.36, 52.87, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_10.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 57.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube1070.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube1070_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube1070_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube1070_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube1070_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_11.geometry} material={nodes.Lift_Lobby_Stairs_11.material} position={[-37.58, 57.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_11.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_11.material} position={[-4.36, 57.87, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_11.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 62.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube1071.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube1071_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube1071_2.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube1071_3.geometry} material={materials['Room Material']} />
        <mesh geometry={nodes.Cube1071_4.geometry} material={materials.Greenery} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_12.geometry} material={nodes.Lift_Lobby_Stairs_12.material} position={[-37.58, 62.85, -32.69]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_12.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_12.material} position={[-4.36, 62.86, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_12.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <mesh geometry={nodes.Cargo_Lift_Lobby_Stairs_13.geometry} material={nodes.Cargo_Lift_Lobby_Stairs_13.material} position={[-4.36, 67.85, -21.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <group position={[-36.16, 67.85, -35.58]}>
        <mesh geometry={nodes.Cube252.geometry} material={materials.Greenery} />
        <mesh geometry={nodes.Cube252_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube252_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Cube252_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube252_4.geometry} material={materials['Light Grey']} />
        <mesh geometry={nodes.Cube252_5.geometry} material={materials['Room Material']} />
      </group>
      <mesh geometry={nodes.Lift_Lobby_Stairs_13.geometry} material={nodes.Lift_Lobby_Stairs_13.material} position={[-38.53, 70.45, -30.45]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Pillars_13.geometry} material={materials.Grey} position={[-35.39, 0, -55.16]} />
      <group position={[-35.47, 72.44, -39.62]} rotation={[-Math.PI, 1.38, -Math.PI]}>
        <mesh geometry={nodes.Cube638.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cube638_1.geometry} material={materials['STEng Logo']} />
        <mesh geometry={nodes.Cube638_2.geometry} material={materials['Light Grey']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/STEngJE.glb')
